### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by haoqing12** [bm2-lab/PanPep#10]
I'm getting the following error, my server doesn't have a GPU, I've downloaded CPU-only Torch, but I still can't solve it, what should I do?

Traceback (most recent call last):
  File "/home/haoq/PanPep-1.0.0-beta/PanPep.py", line 164, in <module>
    model = Memory_Meta(args, config).to(device)
  File "/home/haoq/PanPep-1.0.0-beta/Requirements/Memory_meta.py", line 213, in __init__
    self.models = torch.Tensor().cuda()
  File "/home/haoq/anaconda3/envs/panpep/lib/python3.9/site-packages/torch/cuda/__init__.py", line 210, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest in our work. Deleting the .cuda() in line 213 may solve your problem. We are sorry for that our model can not adapt to the CPU version. We will update our model in the future.

**Comment by haoqing12** [comment]
Thank you very much for your reply.
I have installed the GPU but there is a new error reported. 

Traceback (most recent call last):
  File "/home/haoq/PanPep-1.0.0-beta/PanPep.py", line 280, in <module>
    start = model.meta_forward_score(peptide_embedding.to(device), x_spt.to(device))
  File "/home/haoq/PanPep-1.0.0-beta/Requirements/Memory_meta.py", line 346, in meta_forward_score
    r = self.Memory_module.readhead(peptide[i])[0]
  File "/home/haoq/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/haoq/PanPep-1.0.0-beta/Requirements/Memory_meta.py", line 34, in forward
    w = self.memory(q)
  File "/home/haoq/anaconda3/envs/Pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/haoq/PanPep-1.0.0-beta/Requirements/Memory_meta.py", line 103, in forward
    w = F.softmax(F.cosine_similarity(self.peptide_index+1e-16,query+1e-16,dim=-1),dim=1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
