### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by maheshworpaudel5001** [bm2-lab/PanPep#6]
Hi, I do not see a setup.py file. So, I do not know how do I install it properly in a virtual environment using Conda.

I tried git cloning it. But it complained me of some of the modules that were not installed, which I installed. However, it has been complaining me of other errors of files not being found. 

Here is the snippet of what I am through:
(panpep) [mxp140@r1pl-hpcf-h03 ~]$ python PanPep/PanPep.py --learning_setting zero-shot --input PanPep/Data/Example_zero-shot.csv --output PanPep/Output/i_just_ran_0_shot_output.csv
Traceback (most recent call last):
  File "/gpfs0/home1/gddaslab/mxp140/PanPep/PanPep.py", line 29, in <module>
    aa_dict = joblib.load("./Requirements/dic_Atchley_factors.pkl")
  File "/home/gddaslab/mxp140/anaconda3/envs/panpep/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Requirements/dic_Atchley_factors.pkl'

**Comment by maheshworpaudel5001** [comment]
I have worked out the installation.
